### PR TITLE
belt request

### PR DESCRIPTION
**Pull request by billwestfall**
1.      Our demo to Inner source on the Dojo - a great learning experience (how to summarize the entire Dojo and circle idea), and working with others to communicate that
2.      Adults learn to ride a bicycle - how to adapt your mind which is already stuck (to some degree) in a specific way of thinking and learn something that might otherwise be counterintuitive
3.      How to make toast - systems thinking, this is a good thinking experiment to get folks together in the mind of how to visualize a system, and then the important differences in how we picture systems
4.      Zenshin - focus, like Free Solo. i have learned and embraced this idea of practicing and then effortlessly (or nearly) implementing your practice
5.      theory of constraints - 3 ways to visualize and overcome bottlenecks. i.e. don't worry about the "bottleneck", look at optimizing flow instead
6.      Cynefin - model of flow from chaos to order. I do grok the basics of the model but would need to be embedded again with an organization to see how it plays out in a real world model to completely understand

1.      Duck Rabbit - people viewing the same thing and coming to different conclusions, and how people can change their views. A nice , simple intro to the idea of seeing things through other people's point of view
2.      Ames Window - trapezoid that appears like a rectangle, rotates but appears to oscillate, with pen, pen appears to pass through rotating window. I love the ambiguity of this and reminds me of the entagngled particles, quantum computing topic. This makes me think of the topic different than most people I think, because of my love of ambiguity
3.      Freedom of Chaos - I take this one to heart because I naturally like to improvise (not always successfully) in periods of chaos. But I do like a balance of people who are planners to balance me out on this
4.      Tetris and empathy - I empathize with this, I have become this mostly myself lately. there is a converse of this though, in that there may be a difference between conversations that have outcomes and those that don't. those conversations that have a measurable outcome may have a significant impact of following one pattern or another
5.      spiral dynamics - there was an article you had that was a little more succinct on this ? I think the article might be preferable to the video. from the wikipedia, is the final goal of spiral dynamics to classify or to rank? the idea of state of nature to seeing life as a single thing seems to imply a progression or evolution. i do like the idea of applying it to corporate world though
6.      Backwards bicycle - like the adult bicycle, how to have your brain retrain and be able to learn something new. in this case, it's not only learning something new, but retraining the brain to go against already learned behavior
7.      system metaphor - I think of this natually, my mind often tries to make metaphors/analogies when understanding and describing a system. So I should just keep doing that  :) 

1.      Inside Out 2 - anxiety has to throttled down to allow other emotions to exist, so that they can coexist with each other.  when anxiety was allowed to rule, then sense of self is lost. Then can create a new sense of self that can contain all
2.      Karpman drama triangle - this plays itself out very explicitly in corporate world. victim/bully/savior all played out in my experience. had conversation with wife that this may be due to the hierarchy (feudal) system itself, which empowers dysfunctional mindset

### CODE REVIEW

**Comment by michael-basil** [comment]
@billwestfall  - this  is a great reflection.  Very thorough.

Take one step back ... after going through this cycle of the Dojo ...

Has your emotional awareness, intelligence changed?  If so, in what ways?

Do you show up any differently in conversations by your estimation?  Has anyone else noticed?

Succinctly, what is the value for you from white to green?  What do you think would be a value going from green to red?

Warmly.
Michael 🌿

**Comment by billwestfall** [comment]
> @billwestfall - this is a great reflection. Very thorough.
> 
> Take one step back ... after going through this cycle of the Dojo ...
> 
> Has your emotional awareness, intelligence changed? If so, in what ways?
> 
> Do you show up any differently in conversations by your estimation? Has anyone else noticed?
> 
> Succinctly, what is the value for you from white to green? What do you think would be a value going from green to red?
> 
> Warmly. Michael 🌿

@michael-basil  for emotional intelligence, I would say it might be not far off where I started. I have not moved the needle far with it I think

For difference in conversation, I do think I listen now as hard as I can , and try to weigh the different sides of any topic being discussed. I think I have a more open mind to big topics than I have had in the past, and I'm able to change my mind when the evidence requires it.

For green -> red, I look forward to putting some of the ideas we are talking about into practice, like i did for red belt at SAP. I think there is some value to gain from adapting a practical application of these topics to new life experience I have outside my previous job.
The white -> green has value in exposing myself to new ideas in the learning journey, so that I can be prepared to apply some of them coming up

**Comment by michael-basil** [comment]
Great awareness @billwestfall!

As you go through the red belt progression, I suggest you consider the principle around emotion.  This may be a dimension to put some directionalize focus is another way to put it (expand comfort zone in a different way than we have focused on in the past)

As an illustrative example, something I am working with in my family is to understand when negative emotional waves occur.

Concretely, my son Jack will get sad and overwhelmed when he is first encountering something far outside his comfort zone.   This is a high correlation from my perspective, he and his mother agree.   I first really keyed in on this a few years ago when he was learning to fold a blanket ... now this is a frequent comment ... "what is this like?" ... "I know!  Folding the blanket!"

I'm developing an intuition so that I don't try to "make the wave go away".   I will suggest a "metashift" or paradigm shift or attitude shift, but more and more I just focus now to allow Jack to work through it more independently.

But the thing is ... he is slowly learning that when he moves back into action he feels better (we may revisit the emotion later).  

We talked about Jocko Good and Opposite Action before ... I may re-introduce these concepts as there is a much clearer tie.  To Jack, Lila and Katie ... but also here to this curriculum.

As I improve my emotional intelligence and intuition I notice that others in my tight circles do as well, at least when I'm around!

You are clear for demo on Friday.  Looking forward to this and I am happy to offer support on the red belt progression of course!

Warmly.
Michael 🌿

**Review by michael-basil — APPROVED** [review]
Great reflection and demo @billwestfall!

Belt granted!

Warmly.
Michael 🌿

**Pull request merged**
