### PR TITLE
feat: Add Dunning Kruger

### PR DESCRIPTION
**Pull request by michael-basil**
Want to come out of the gate with red level introducing this important concept to help conceptualize what happens on this journey of discovery.

### CODE REVIEW

**Comment by michael-basil** [comment]
Which part is in dispute?  I didn't mean to introduce controversy, but always glad to unpack it!

**Comment by billwestfall** [comment]
> Which part is in dispute? I didn't mean to introduce controversy, but always glad to unpack it!

@michael-basil  : Dunning Kruger was a study looking at point in time record of individuals at competency levels. The article states a "metacognition" growth in individuals, that would entail a multiyear study, and has never been done AFAIK. Maybe item for Friday discussion?

**Comment by michael-basil** [comment]
Sounds good!  It was interesting because I was going to put in Dale's article about Senpai which mentioned the effect and then looked up some articles and liked this one as a great way to inflect into the red level.

Once we really get into a domain and learn a bit about it we feel like the pond may actually be an ocean!

**Comment by michael-basil** [comment]
Decided against this after more consideration.

**Pull request closed without merging**
