### PR TITLE
refactor: Domain cleanup

### PR DESCRIPTION
**Pull request by michael-basil**
Doing a thought experiment.

1. Should we eliminate the domains which do not have active Sensei and full curriculum?  My leaning is towards yes.

2. What will be the best experience for people coming in currently?  If it isn't clear these domains will take off then perhaps it keeps the focus on what is trending as the nucleus forms.

3. Does removing these give a fresh look at what the spirit of putting both of Agile and InnerSource into the Dojo in the first place?  I think yes.

I have an idea floating around of a Mixed Domain.

Agile InnerSource: Lightweight, disciplined, scalable

This is influenced and or correlated by Agile training I have been doing with Scrum Alliance and Scaled Agile .. plus ongoing conversations about the intersection of Agile and InnerSource with InnerSource Commons Foundation.

Perhaps Dojo Center is a Netural Zone where people of both or one of the disciplines could come together to offer a blended pathway of convergence of these coherent complimentary practices.

I could see such a blended domain being of benefit and endorsement of various organizations without having to overcommit.

@billwestfall @aphor @anuolu @jimmanzzullo I am curious to your thoughts on this if you have a moment.

I have not brought this for review at this time and wouldn't until I had alignment with Bill at minimum as he has been nearest to the conversations I speak of, even if hearing the pulse from my perspective.

### CODE REVIEW

**Comment by billwestfall** [comment]
how about keeping one non implemented domain as an example of how a new one is created?

**Comment by michael-basil** [comment]
That was the original thought. 

Perhaps Agile InnerSource is such a concept.

Maybe there is a different example. 

To me this is the utility of contending with the Void thought experiment.

Create a potential void. 

See what surfaces.

I also thought that our presentation covers the idea of other domains.

When someone comes in fresh do we want to influence and bias towards thinking of what else can be there or to engage what is already there first? 

The framing of the question I just posed suggests my bias of course.

**Comment by billwestfall** [comment]
the void might be useful, I understand now  :)  👍

**Comment by michael-basil** [comment]
I've moved this into review.   After conversations today with ISC I sense that the void will be more useful to allow that which should materialize come through organically and not overly prescriptive based on what we have done before.

I also planted the seed with @jimmanzzullo.

So I think if there is an approval this is an appropriate change to make understanding we are open to what may come back in following on whether it be Agile, InnerSource, Agile InnerSource or something we have not envisioned concretely in this conversation.

So @billwestfall (@jimmanzzullo @aphor @anuolu) or anyone else who has write access (in the Senpai team), with the approval I would merge it!

**Review by billwestfall — APPROVED** [review]
+1

**Pull request merged**
