### PR TITLE
feat: Uplift Mindset Principles

### PR DESCRIPTION
**Pull request by michael-basil**
Distilling further influenced by some time pressure from upcoming presentation to Cloud Security Office Hours.

Looking for commentary at this point, once everyone has had a reasonable chance to weigh in then can move for approval.

### CODE REVIEW

**Review by billwestfall — APPROVED** [review]
+1

**Comment by michael-basil** [comment]
I am going to leave it open for others to comment!

**Comment by michael-basil** [comment]
Moving forward with merge as meetings today may discuss this.

**Review by aphor — COMMENTED** [review]
good change of framing

**Pull request merged**
