### PR TITLE
refactor: Mindset Mission Wholeheartedness

### PR DESCRIPTION
**Pull request by michael-basil**
After doing some deep mindset work this past weekend this adjustment came to surface.

@abkaufmann @billwestfall @aphor @jimmanzzullo @nbasil - please feel free to comment.

However, do not approve or merge.  

I would like to make sure to get a chance to see how this (proposed change idea) resonates or not with @anuolu.

Warmly.
Michael Basil 🌿

### CODE REVIEW

**Comment by abkaufmann** [comment]
I like the update!

**Review by billwestfall — COMMENTED** [review]
I like it

**Review by aphor — APPROVED** [review]

**Comment by anuolu** [comment]
I like this change.

**Review by anuolu — APPROVED** [review]

**Comment by michael-basil** [comment]
Thanks all!

**Pull request merged**
